apache/hbase-connectors

bin/hbase-connectors, hbase-connectors-assembly/pom.xml, hbase-connectors-assembly/src/main/assembly/connector-components.xml, hbase-connectors-assembly/src/main/assembly/hbase-connectors-bin.xml
Assembly layout and name is harmonized with the main project:
* jar files are placed under lib
* final assembly name is hbase-connectors-<version>-bin.tar.gz
=> HBASE-22210 Fix hbase-connectors-assembly to include every jar

dev-support/Dockerfile
we can work out how to properly get findbugs or spotbugs after getting precommit building.
=> HBASE-22674 remove findbugs installation via apt-get because it brings in openjdk-jre and we need a jdk.

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/DefaultSource.scala, spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/datasources/Utils.scala, spark/hbase-spark/src/test/scala/org/apache/hadoop/hbase/spark/DefaultSourceSuite.scala, spark/hbase-spark/src/test/scala/org/apache/hadoop/hbase/spark/HBaseCatalogSuite.scala
* insert always uses the given mapping
* supports the following types:
* binary
* boolean
* byte, short, int, long
* float, double
* date, timestamp
* string
=> HBASE-22711 Spark connector doesn't use the given mapping when inserting data

spark/pom.xml
Jackson security issues：
A Polymorphic Typing issue was discovered in FasterXML jackson-databind before 2.9.10. It is related to com.zaxxer.hikari.HikariDataSource. This is a different vulnerability than CVE-2019-14540.
https://nvd.nist.gov/vuln/detail/CVE-2019-16335
A Polymorphic Typing issue was discovered in FasterXML jackson-databind before 2.9.10. It is related to com.zaxxer.hikari.HikariConfig.
https://nvd.nist.gov/vuln/detail/CVE-2019-14540
=> HBASE-23075 Upgrade jackson version

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/DefaultSource.scala
HBaseRelation.createTable checks table existence with HBaseAdmin.isTableAvailable method in DefaultSource.scala (createTable). This is unfortunate, because it can return false while splitting, so createTable will fail. It should use tableExists.
=> HBASE-23348 Spark's createTable method throws an exception while the table is being split

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/datasources/HBaseTableScanRDD.scala
When the `hbase-spark` module is compiled under the scala 2.12 environment, the following error appears in line 216 of the `org.apache.hadoop.hbase.spark.datasources.HBaseTableScanRDD` class:
```shell
[ERROR] [Error] /path/hbase-connectors/spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/datasources/HBaseTableScanRDD.scala:216: ambiguous reference to overloaded definition,
both method addTaskCompletionListener in class TaskContext of type [U](f: org.apache.spark.TaskContext => U)org.apache.spark.TaskContext
and  method addTaskCompletionListener in class TaskContext of type (listener: org.apache.spark.util.TaskCompletionListener)org.apache.spark.TaskContext
match argument types (org.apache.spark.TaskContext => Unit)
```
I solve this bug by changing the origin line:
```scala …
```
=> HBASE-24088 Solve the ambiguous reference for scala 2.12

dev-support/jenkins/hbase-personality.sh
The previously used check does not work when a change is made in the parent 'spark' module so the precommit job fails because the generated classes are missing when executing test-compile. With the 'spark' regex check it matches all spark modules in the hbase-connectors repository.
https://ci-hadoop.apache.org/job/HBase/job/HBase-Connectors-PreCommit/job/PR-61/2/artifact/yetus-precommit-check/output/branch-compile-spark.txt
=> HBASE-25236 Run package phase on spark modules

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/HBaseContext.scala
bulkLoad should support the user to pass in the version timestamp just like Put
=> HBASE-24230 Support user-defined version timestamp when bulk load data

spark/README.md, spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/HBaseContext.scala, spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/datasources/Utils.scala
Currently hbase-spark connector only works with Spark 2.x. Apache Spark 3.0 has been relesead in June 2020.
This addresses the changes needed to run the connector with Spark 3.0 and also to be able to compile the connector using Spark 3.0 as a dependency.
This has been manually tested with Apache Spark 3.0.1 and HBase 2.2.4.
=> HBASE-25326 Allow running and building hbase-connectors with Apache Spark 3.0

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/datasources/NaiveEncoder.scala, spark/hbase-spark/src/test/scala/org/apache/hadoop/hbase/spark/DynamicLogicExpressionSuite.scala
This PR adds an additional test case to `DynamicLogicExpressionSuite` that performs the main test using Long numbers and fixes the decoding of `LongEnc` values in the `filter()` method of `NaiveEncoder`.
=> HBASE-26211 Fix decoding of Long values in NaiveEncoder

kafka/hbase-kafka-proxy/src/main/java/org/apache/hadoop/hbase/kafka/KafkaTableForBridge.java, pom.xml, spark/README.md, spark/hbase-spark/pom.xml, spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/HBaseContext.scala, spark/hbase-spark/src/test/java/org/apache/hadoop/hbase/spark/TestJavaHBaseContext.java, spark/hbase-spark/src/test/scala/org/apache/hadoop/hbase/spark/BulkLoadSuite.scala, spark/pom.xml
This proposes to bump up the default versions used by HBase-connectors to recent versions, in particular for HBase, Spark, and Hadoop:
HBase is upgraded to 2.4.9, Spark to 3.1.2, Hadoop to 3.2.0.
This proposes also to make Spark 3 and Hadoop 3 default version (as opposed to Spark 2 and Hadoop 2).
Additional minor changes to the code are proposed/needed to compile the connector with HBase 2.4.9.
=> [HBASE-26534] Update HBase version to 2.4, make Hadoop 3 and Spark 3 default versions.

pom.xml
- hbase-connector fails to build with -Prelease after maven-enforcer-plugin upgraded to 3.0.0 from 3.0.0-M3
=> HBASE-26664 hbase-connector upgrade extra-enforcer-rules to 1.5.1

hbase-connectors-assembly/pom.xml, hbase-connectors-assembly/src/main/assembly/hbase-connectors-bin.xml, hbase-connectors-assembly/src/main/resources/supplemental-models.xml, pom.xml
- fix NOTICE.aggregate generation
please see the other discussion on #41 , and I think #41 should be closed and continue the discussion here.
=> HBASE-22338 LICENSE file only contains Apache 2.0

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/HBaseContext.scala, spark/hbase-spark/src/test/scala/org/apache/hadoop/hbase/spark/BulkLoadSuite.scala
The reason for the problem was the usage of the default FileSystem instances for creating and using staging stuff. Now we use the staging path to obtain the FileSystem instance, so it should work correctly for any different from the hdfs schema.
The test uses a local filesystem and doesn't load files to the table due to limitations:
1. HBase minicluster uses hdfs only, and there is no way to specify a custom hbase.rootdir for that. So the load would not work because the staging dir is on a different filesystem
2. I tried to get hadoop-aws mock implementation working for an external filesystem, but that would require making the tests for this module published first
Both those two bullets can be addressed in separate jiras if required.
=> HBASE-27630: hbase-spark bulkload stage directory limited to hdfs only

spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/DefaultSource.scala, spark/hbase-spark/src/test/scala/org/apache/hadoop/hbase/spark/DefaultSourceSuite.scala
This PR fixes an incorrect rowkey pushdown caused by miscalculation of overlapping scan ranges, which occurs when spark sql optimizer generates pushdown filters in such an order that a scan range that comes later overshadows the previous scan range.
=> HBASE-26863 fix incorrect rowkey pushdown

dev-support/.scalafmt.conf, dev-support/eclipse.importorder, dev-support/hbase_eclipse_formatter.xml, dev-support/license-header, pom.xml
- Added the base plugin to pom.xml (similar to other hbase repos)
- Extended the plugin to support formatting of scala code / headers
- Added the files required by the base plugin ( copying them from hbase repo)
- Added a new file .scalafmt.conf, which is required by spotless for scala (copied from spark repo)
- Made changes to fix docstring param new line issue and used latest scalafmt version i.e. 3.7.12
=> HBASE-27178 Use spotless to format code (including scala code)

spark/hbase-spark/pom.xml, spark/hbase-spark/src/main/scala/org/apache/hadoop/hbase/spark/datasources/HBaseTableCatalog.scala, spark/pom.xml
In https://issues.apache.org/jira/browse/HBASE-28137 to support Spark 3.4 the scala-parser-combinators was added as direct dependency to HBase Spark Connector. This was needed as Spark 3.4 is not using scala-parser-combinators and it is not inherited as transitive dependency.
But this solution has a disadvantage. As the HBase Spark Connector assembly jar does not include any 3rd party libraries the scala-parser-combinators must be added to the spark classpath for HBase Spark Connector to work. A much better solution is to replace scala.util.parsing.json with org.json4s.jackson which is used by Spark core, see https://github.com/apache/spark/blob/branch-3.4/core/pom.xml#L279-L280.
=> HBASE-28152. Replace scala.util.parsing.json with org.json4s.jackson

pom.xml
This change will allow hbase spark connector to compile on mac M1.
=> HBASE-28606 Support for build on mac M1

kafka/hbase-kafka-proxy/src/main/java/org/apache/hadoop/hbase/kafka/KafkaBridgeConnection.java
- Add missing method setRequestAttribute added in HBASE-27657
=> HBASE-28790 hbase-connectors fails to build with hbase 2.6.0

hbase-connectors-assembly/src/main/resources/supplemental-models.xml, pom.xml, spark/hbase-spark-it/pom.xml, spark/hbase-spark/pom.xml
also update
* hadoop to 3.4.1
* hbase-thirdparty to 4.11.0
* mockito to 4.11.0
* surefire to 3.5.2
* commons-lang to 3.17.0
=> HBASE-29287 Update HBase version used in connectors to 2.6.2

pom.xml, spark/hbase-spark-it/pom.xml, spark/hbase-spark/pom.xml, spark/pom.xml
- Remove EOL'ed gmaven-plugin which is unnecessarily too complex and does not work with JDK17
- Refactor flags for UT and IT for ease of profile based run
- Copy JDK17 flags from HBase and Spark
- Add profile for JDK11 and JDK17 build
=> HBASE-28382 Support building hbase-connectors with JDK17
